### ISSUE TITLE
option to execute only "current" query

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#11]
The way sequel pro only ran the "current" query (the query that had the keyboard curser) always made a lot of sense to me.

I *sometimes* want to execute multiple queries at once, but usually I'm editing and re-executing the same query multiple times. If I have auxiliary queries I either have to keep them in a separate window or comment them out. 

`cmd + enter` to execute the "current" query or selection and `cmd + option + enter` to execute all queries would be great.

**Comment by danillos** [comment]
The Sequel Pro separate the queries by `;` when the pointer is over the query, it shows the query highlighted, and on hit `cmd + r` only run this current query.

I really like this approach.

<img width="381" alt="screen shot 2015-07-08 at 8 28 11 pm" src="https://cloud.githubusercontent.com/assets/54908/8584710/e2635314-25af-11e5-879d-cc97c1361151.png">

**Comment by jakob** [comment]
I started to work on this. Try the latest build: [Postico 2015-08-17](http://eggerapps-downloads.s3.amazonaws.com/postico-2015-08-17.zip)

In this build, Postico executes only the current statement. You can highlight multiple statements to execute more than one. However, after implementing this, I found out that I will need to completely rewrite the way the query history works; it makes no sense the way it is now (replacing the full text field doesn't make sense when you have many queries in the text field)

**Comment by danillos** [comment]
Thanks @jakob, this is awesome.

I'm testing here, so far everything is fine, I'll test it more along this week.

I noticed that when I hit Enter between two queries has a blink in the queries with the highlight.

About the Query History, removing the other query sometimes is annoying, because sometimes We create a group of queries to do the work more easily, and now we can't back to this group using the query history, because it shows only the last one executed. But I understand your point of view too.

thanks @jakob

**Comment by qwesda** [comment]
Great that this feature is coming!

I also noticed some minor issues on the "edges" of queries:
- any cursor position should activate a query unless there are no queries in the editor
- I think a good logic would be that a query includes a semicolon plus `/[ \t]*\n?/` – everything after this regex belongs to the next query
- a special case would be a `--` comment, which should still belong to the previous query unless they are separated by a linebreak
- anything before the first query belongs to the first query and anything after the last query belongs to the last query

the execute button should be visually disabled if no query is activated/selected

**Comment by jakob** [comment]
@qwesda I'm not sure that a query should always be active. If the insertion point is between to queries, I think it's better to make no query active.

The button should be visually disabled, but I just realised that the button doesn't look deactivated on Yosemite. Damn Apple for changing button styles every year.

Comments like below should belong to the query, that's a good point.
```SQL
select 1; -- select one
```

**Comment by danillos** [comment]
Hi @jakob,

When the pointer is in the beginningor end of the row, the query is not highlighted.

<img width="518" alt="screen shot 2015-08-21 at 4 41 43 pm" src="https://cloud.githubusercontent.com/assets/54908/9417529/8b6ebe68-4823-11e5-884e-eb4c08b9e76a.png">


<img width="524" alt="screen shot 2015-08-21 at 4 37 40 pm" src="https://cloud.githubusercontent.com/assets/54908/9417489/2359edb6-4823-11e5-9375-9d3f76775fd8.png">

**Comment by jakob** [comment]
Hi @qwesda and @danillos, I've now improved the query detection code. I've implemented most of your suggestions and fixed the problem when the cursor is at the end of the row. Would you be interested in testing it?

Here's the latest build:
http://eggerapps-downloads.s3.amazonaws.com/postico-2015-09-10.zip

**Comment by danillos** [comment]
Nice Jakob, I’m testing it right now.

**Comment by danillos** [comment]
Hi @jakob, I found this issue http://quick.as/7bghge28

Sorry about the music =/

**Comment by danillos** [comment]
Hi @jakob, I found more one issue http://quick.as/6ngcqa5v

**Comment by jakob** [comment]
Thanks for the quick feedback. I fixed the first issue:
http://eggerapps-downloads.s3.amazonaws.com/postico-2015-09-11.zip

I'm not sure what the problem is with the second video. Could you explain the problem in more detail?

**Comment by danillos** [comment]
When I press cmd + / the query is commented, but when a press again, it don't uncomment the query.

Only happens with multiple lines comments.

In the public build is works fine, but with that build don't.

**Comment by qwesda** [comment]
For me everything works as expected.
The only minor thing would be that trailing whitespace after the last query should belong to the last query – analog to all whitespace before to the first query (which is already handeled).

Anyway, great job! this made postico a lot more useful to me!

**Comment by qwesda** [comment]
Maybe you could add `cmd + alt + <return>` as _execute all queries_
`cmd A` + `cmd <return>` does of course the same, but it also resets the cursor position

**Comment by qwesda** [comment]
I also have the same issue as @danillos `cmd + /` only increases the comment level, but uncommenting doesn't work.

I also found that *execute selection* is no longer working.

**Comment by jakob** [comment]
I've now fixed the commenting issue in version 0.27. Execute selection also works again now. You can read about all the other new things in the changelist: 
https://eggerapps.at/postico/changelist.html

I've decided to disable the execute button when the cursor is on a blank line that doesn't belong to a statement. I tried making it so that it executes the nearest statement, but I couldn't find a good rule which one is the nearest statement (should it be the statement above or below?). Everything I tried seemed confusing in some circumstances.

**Comment by qwesda** [comment]
Hitting `CMD+A` in the query editor disables the execute button

**Comment by qwesda** [comment]
the issue from @danillos that `CMD + /` only increases the comment level is also still present

**Comment by jakob** [comment]
@qwesda Jesus, you are right; it seems a last minute change broke the query again. I'll get to work on those immediately.

**Comment by jakob** [comment]
@qwesda Could you try if this build works: [Postico 0.28](https://eggerapps-downloads.s3.amazonaws.com/postico-0.28.zip)

**Comment by qwesda** [comment]
- `CMD + A` is working
- `CMD + /` is working
- `CMD + OPTION + <ENTER>` is still missing

**Comment by jakob** [comment]
Just released 0.28. The final version also adds support for Cmd-Option-Enter to execute all queries.
Details & Download link: https://eggerapps.at/postico/changelist.html
