### ISSUE TITLE
Cast to TEXT applied to UUID columns in the UI filter

### ISSUE THREAD

**Issue by vlad-at-yteq** [jakob/Postico#184]
Hi Jakob,

First of all congrats, Postico is a great tool!

There is an issue in the UI filter on UUID columns which make querying very slow on sizeable amount of data. t the moment it's done this way:

uuid_col::text = '<uuid literal as string>'

The ::text cast causes UUID index to be skipped. So it should rather do the following:

uuid_col = '<uuid literal as string>'

Postgres will apply implicit cast to '<uuid literal as string>' as '<uuid literal as string>'::uuid.

I would appreciate if this could be fix (I imagine a fix would be fairly trivial).

**Comment by jakob** [comment]
Hi! Postico 1.0.5 now treats UUIDs as numbers when filtering, which should fix this issue. Thanks for reporting it!

**Comment by qwesda** [comment]
I think uuid columns still get treated as a string if the filter is activated by right clicking on the column header and selecting `Filter ...` from the context-menu.
