### ISSUE TITLE
Sorting a float column in query results sorts incorrect

### ISSUE THREAD

**Issue by canuk** [jakob/Postico#744]
## What did you do?

I made a query that calculated the percent change and put it into a column
When I click on the column header in the query results to sort it, it sorts by the "absolute number on the right of the decimal"
For example,  it sorts

-0.2
-0.04
-0.265
0.01
0.04
0.4
0.05
...

## What did you expect to happen?

- I expected to see it sort by the value of the field
-0.04 would be before -0.2 for example.

## What actually happened?

Here is an example of the sort:
-0.2
-0.04
-0.265
0.01
0.04
0.4
0.05
0.91
0.112
...

## What software versions are you using?

Postico version:  
Version 1.5.14 (6816)

macOS version:  
10.15.7

PostgreSQL version:  
PostgreSQL 9.6.18 on x86_64-apple-darwin14.5.0, compiled by Apple LLVM version 7.0.2 (clang-700.1.81), 64-bit

**Comment by jakob** [comment]
Thanks for reporting this!

We've just released an update that fixes this issue.

Please download Postico 1.5.16 from https://eggerapps.at/postico/

**Comment by canuk** [comment]
Hi Jakob!

Thanks for responding, but the issue is still happening, only now when I'm sorting integers in a filtered view.
For example it's sorting an integer column ascending:
1
1
10
11
2
2
...
Postico version:
Version 1.5.16 (7440)

macOS version:
10.15.7

PostgreSQL version:
PostgreSQL 9.6.18 on x86_64-apple-darwin14.5.0, compiled by Apple LLVM version 7.0.2 (clang-700.1.81), 64-bit

**Comment by jakob** [comment]
@canuk What's the data type of the column? If it's a textual column, it's supposed to sort like this.

If you mouse over the column title, it should show a tooltip with the data type.

(earlier versions of Postico used a numeric sort that tried to correctly sort numbers in text, but it caused issues for timestamps, hexadecimal numbers, etc. So now we use numeric sort only for numeric columns.)

**Comment by canuk** [comment]
Aha! Sorry to bother you. It turns out it was a column of integers... however the column type was varchar. My mistake.  The other fix (on a float column) works great! Thanks so much.
